import random

LEVELS = [
    'House',
    'Trump Castle',
    'Milk Sea',
    'Fairy Forest',
    'Star Hill',
    'Ice-Fire Mountain'
]

FACES = [
    'a HERO', 'a NINJA', 'a ROBOT', 'an ALIEN', 'a FIGHTER', 'a MONSTER', 'a GHOST', 'a ?'
]
BODIES = [
    'in ARMOR', 'with WINGS', 'JET', 'CYBORG', 'BOAT', 'BUGGY', 'TANK', 'with a ? body'
]
WEAPONS = [
    'PARASOL', 'BOOMERANG', 'SHURIKEN', 'BALL', 'PENCIL', 'CRYSTAL', 'FLOWER', 'MELODY'
]
VOWELS = 'aeiou'
NAMES = [
    'Ab?',
    'Ad?m',
    'Al?x',
    'Am?s',
    'And?',
    'Ann?',
    'Arb?',
    'Ar?a',
    'Ax?m',
    'Bl?m',
    'Bl?p',
    'B?ar',
    'B?ck',
    'B?rt',
    'B?b',
    'B?d',
    'B?gs',
    'B?ll',
    'B?n',
    'B?ne',
    'B?rg',
    'B?rr',
    'B?th',
    'B?x',
    'C?ra',
    'C?rm',
    'C?rn',
    'C?ve',
    'C?te',
    'Ch?d',
    'Ch?s',
    'Ch?t',
    'D?b',
    'D?g',
    'D?me',
    'D?n',
    'D?ne',
    'D?nk',
    'D?ng',
    'D?rg',
    'D?rk',
    'D?tt',
    'D?ve',
    'Ell?',
    'Emm?',
    'En?',
    'Ev?',
    'Ev?n',
    'Fl?p',
    'Fl?r',
    'F?nn',
    'F?st',
    'F?x',
    'Gab?',
    'G?d',
    'G?rd',
    'Han?',
    'H?ra',
    'H?mm',
    'H?ck',
    'H?nk',
    'H?ny',
    'H?y',
    'Ink?',
    'Ir?',
    'J?ff',
    'J?m',
    'J?n',
    'J?ne',
    'J?nk',
    'K?d',
    'K?i',
    'K?ng',
    'K?t',
    'K?t?',
    'Le?',
    'L?na',
    'L?ra',
    'L?re',
    'L?rp',
    'L?v',
    'L?ve',
    'L?x',
    'L?zz',
    'Mar?',
    'Mik?',
    'M?me',
    'M?ry',
    'M?s',
    'M?ss',
    'M?tt',
    'M?x',
    'Nan?',
    'Nav?',
    'N?an',
    'N?ck',
    'N?mm',
    'N?mo',
    'N?na',
    'N?ss',
    'Ob?',
    'Ot?s',
    'P?a',
    'P?ar',
    'P?ch',
    'P?gg',
    'P?ng',
    'P?ps',
    'Qu?c',
    'Qu?d',
    'Qu?p',
    'R?a',
    'R?bo',
    'R?dd',
    'R?gg',
    'R?n',
    'R?na',
    'R?se',
    'R?t',
    'R?va',
    'R?x',
    'R?xy',
    'R?y',
    'Sk?t',
    'Sm?l',
    'Sp?m',
    'S?l',
    'S?m',
    'S?n',
    'S?ra',
    'S?th',
    'St?b',
    'St?r',
    'St?v',
    'S?zy',
    'The?',
    'Th?m',
    'Th?s',
    'To?d',
    'Tr?y',
    'T?dd',
    'T?m',
    'T?na',
    'T?nk',
    'T?ny',
    'T?ra',
    'T?y',
    'Un?',
    'Veg?',
    'V?n',
    'V?ra',
    'W?ll',
    'W?h',
    'W?t',
    'Xen?',
    'Y?ng',
    'Yur?',
    'Z?ra',
    'Z?nd',
    'Z?no',
    '?ck',
    '?dd',
    '?ggy',
    '?gor',
    '?lan',
    '?lia',
    '?lly',
    '?lsa',
    '?m',
    '?my',
    '?ng',
    '?rb',
    '?ric',
    '?rr',
    '?va',
    '?x',
]

def cocoron_char():
    face = random.choice(FACES)
    body = random.choice(BODIES)
    weapon = random.choice(WEAPONS)

    return f"{face} {body}, whose weapon is a {weapon}"


def cocoron_rando():
    levels = LEVELS[:]
    random.shuffle(levels)
    level_order = ', '.join(levels)
    char = cocoron_char()
    response = [
        f"Your level order is: {level_order}",
        f"Your starting character is {char}.",
        "Say !cchar to get another character."
    ]
    return response


if __name__ == '__main__':
    print(cocoron_rando())
